Pablo Jordán
sistemas-de-informacion/docs pull request #195
Opened 2021-03-01 11:17 UTC by pabloJordan24

2021-03-01 21:05 UTC, fjlopez requested changes
Si se corrige el primer enlace y es un caso de estudio la nota sería 10, si no la nota sería de 7.

2021-03-01 21:05 UTC, fjlopez commented on fracasar-con-erp.md
> +- **ERP desconocido y empresa encargada de embotellar refrescos (soft drink bottler)** : [Cómo la falta de comunicación y de soporte acabaron condenando a una gran empresa dedicada al embotellado de
Enlace no corresponde con el contenido.

2021-03-01 21:05 UTC, fjlopez commented on fracasar-con-erp.md
> +- **SAP y Diageo** : [Cómo la mala negociación de términos y condiciones puede acabar en juicio](https://www.informationweek.com/strategic-cio/take-a-wrong-turn-with-erp-and-wind-up-in-court/a/d-id/1
Validado

2021-03-02 17:02 UTC, pabloJordan24 commented on fracasar-con-erp.md
> +- **ERP desconocido y empresa encargada de embotellar refrescos (soft drink bottler)** : [Cómo la falta de comunicación y de soporte acabaron condenando a una gran empresa dedicada al embotellado de
Me había confundido. He añadido el nuevo caso de estudio del año 2005.

2021-03-03 21:22 UTC, merged