Alejandro Magallón
sistemas-de-informacion/docs pull request #196
Opened 2021-03-01 18:46 UTC by alecron

2021-03-01 21:11 UTC, fjlopez requested changes
Los enlaces propuestos no aportan información adicional. Debes buscar **casos nuevos** o **mejoras sustanciales** sobre los existentes. ¡Debes intentarlo otra vez! Busca en Google o en [CIO](https://www.cio.com/).

2021-03-02 20:36 UTC, alecron commented
He añadido un caso en 2007 y otros dos en 2018

2021-03-03 21:25 UTC, fjlopez approved these changes
Con estas tres aportaciones es un 8.

2021-03-03 21:25 UTC, fjlopez commented on fracasar-con-erp.md
> +**SAP y una cadena de joyerías de Colorado:**
Validado

2021-03-03 21:25 UTC, fjlopez commented on fracasar-con-erp.md
> +**ERP no especificado y una compañía de venta de productos metálicos:**
Validado

2021-03-03 21:25 UTC, fjlopez commented on fracasar-con-erp.md
> +**ERP no especificado y compañía de venta de productos electrónicos:**
Validado

2021-03-03 21:25 UTC, merged