Pull Request - Javier Morón - 737908
sistemas-de-informacion/docs pull request #200
Opened 2021-03-02 18:26 UTC by JMGhoster

Añadidos 5 artículos y casos de estudio.

2021-03-03 21:37 UTC, fjlopez requested changes
Tienes un 10 en cuanto añadas un pequeña explicación o amplíes la existente de cada caso, en particular resaltando algo que esté en tus aportaciones.

2021-03-03 21:37 UTC, fjlopez commented on fracasar-con-erp.md
> +[ERP Implementation Failure In Hershey's](https://es.slideshare.net/purohit1323/erp-failure-implementation-failure-hershey-foods-corporation) (Fuente: Lorena Mehavilla), [Case study on ERP success(Ca
Validado. Complementa a los anteriores

2021-03-03 21:37 UTC, fjlopez commented on fracasar-con-erp.md
> +- **Unisys y el estado de [Idaho](http://www.idaho.gov/)**: [The Woe of Idaho: How Ignoring End-Users Derailed an ERP Implementation](http://panorama-consulting.com/the-woe-of-idaho-how-ignoring-end-
Validado. Complementa al anterior.

2021-03-03 21:37 UTC, fjlopez commented on fracasar-con-erp.md
> +- **SAP (instalado por IBM) y [Bridgestone](http://www.bridgestone.com/)**: [PR finger pointing: IBM and Bridgestone wrangle over failed ERP](http://www.zdnet.com/article/pr-finger-pointing-ibm-and-b
Validado, complementa al anterior.  Falta una pequeña explicación del caso.

2021-03-03 21:37 UTC, fjlopez commented on fracasar-con-erp.md
> +[The Hidden S/4 HANNA Failure at LeasePlan](https://www.brightworkresearch.com/saphana/2019/11/10/the-hidden-s-4hana-failure-at-leaseplan/) (Fuente: Alex Sanz) [Case Study 10: LeasePlan Paid $100 Mil
Validado complementa al anterior. Falta una pequeña explicación del caso.

2021-03-03 21:37 UTC, fjlopez commented on fracasar-con-erp.md
> +[Lidl SAP main problems, why it fails?](https://www.thirdstage-consulting.com/lessons-from-an-sap-failure-at-lidl/) (Fuente: Jorge Rambla Gonzalez) [Case Study 12: Lidl’s €500 Million SAP Debacle](ht
VAlidado, falta una ampliación de la explicación del caso.

2021-03-05 11:15 UTC, JMGhoster commented
Ya están actualizadas las explicaciones de los casos, con el año de inicio y una breve descripción. Las he colocado después de la primera noticia, no de la que he agregado yo.

La ampliación de la explicación del caso de Lidl se encuentra escrita después de mi noticia.

2021-03-07 18:40 UTC, fjlopez approved these changes

2021-03-07 18:42 UTC, merged