Update insider-threat.md - Gari
sistemas-de-informacion/docs pull request #395
Opened 2024-03-18 17:33 UTC by Garicore01

2024-03-25 09:31 UTC, fjlopez requested changes
La estrategia está mal enfocada. Si no actualizas la estrategia la nota será un 7.

2024-03-25 09:31 UTC, fjlopez commented on insider-threat.md
> +* **Estrategia**: Morris debería haber utilizado un sistema de detección de anomalías en la red, de manera que rápidamente pudiera detectar el impacto que estaba provocando su código. Esta estrategia
Repiensa la estrategia. Morris no es quien debería pensarla/aplicarla.

2024-04-01 07:10 UTC, Garicore01 commented on insider-threat.md
> +* **Estrategia**: Morris debería haber utilizado un sistema de detección de anomalías en la red, de manera que rápidamente pudiera detectar el impacto que estaba provocando su código. Esta estrategia
La Universidad de Cornell debería haber utilizado un sistema de detección de anomalías en la red, de manera que rápidamente pudiera detectar el impacto que estaba provocando el programa de Morris. Esta estrategia le habría permitido identificar la propagación del gusano y tomar medidas correctivas de manera oportuna. Al implementar esta solución, la Universidad de Cornell podría haber mitigado el daño causado por el ataque y reducido su impacto en la red.

2024-04-03 15:17 UTC, fjlopez approved these changes

2024-04-03 15:18 UTC, merged

2024-04-03 15:18 UTC, fjlopez commented
Tras la corrección la nota es un 10.