Alvaro de Francisco 838819
sistemas-de-informacion/docs pull request #397
Opened 2024-03-20 19:52 UTC by unizar-adf

2024-03-25 09:40 UTC, fjlopez requested changes
Si se aporta dicho enlace, la nota final sería de 10. Si no se refina el enlace, la nota final sería de 8.

2024-03-25 09:40 UTC, fjlopez commented on insider-threat.md
> +  * **Solución**: Oracle Human Capital Management Cloud [(Oracle HCM)](https://www.oracle.com/human-capital-management/) ofrece funcionalidades avanzadas para la gestión del talento, incluyendo la de
Dado que Oracle HCM es una mega-suite, necesitaría un enlace dentro de https://www.oracle.com/human-capital-management/ que estuviera directamente relacionado con la estrategia.

2024-04-11 12:40 UTC, unizar-adf reviewed
he cambiado el enlace al apartado de talent managment

2024-04-11 19:46 UTC, fjlopez approved these changes

2024-04-11 19:47 UTC, merged

2024-04-11 19:47 UTC, fjlopez commented
Se da por válida. La nota es ahora 10.